image: uber/android-build-environment:latest

pipelines:
  tags:
    '**':
      - step:
          script:
            - unset ANDROID_NDK_HOME
            - ./build.sh 0
            - . ./setup_export.sh
            ##########  UPLOAD TO BITBUCKET DOWNLOADS ##########
            # Instructions to setup the next line. https://confluence.atlassian.com/bitbucket/deploy-build-artifacts-to-bitbucket-downloads-872124574.html
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"${LATEST_APK}"

  branches:
    develop:
      - step:
         script:
           - unset ANDROID_NDK_HOME
           - ./build.sh 1
           - . ./setup_export.sh
            ##########  UPLOAD TO BITBUCKET DOWNLOADS ##########
            # Instructions to setup the next line. https://confluence.atlassian.com/bitbucket/deploy-build-artifacts-to-bitbucket-downloads-872124574.html
           - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"${LATEST_APK}"
